version: '3.3'
services:
  sms:
    image: bosagora/acc-sms:latest
    container_name: sms
    ports:
      - '7000:7000'
    restart: always
    environment:
      HOST_IP: 0.0.0.0
      HOST_PORT: 3300
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
